# Generated by Django 3.1.5 on 2021-01-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Miasto', 'verbose_name_plural': 'Miasta'},
        ),
    ]
